services:
  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - TZ=America/Phoenix
      - HTTP_PROXY=${BD_HTTP_PROXY}
      - HTTPS_PROXY=${BD_HTTP_PROXY}
      - NO_PROXY=${SERVER_NO_PROXY}
