services:
  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - TZ=America/Phoenix
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${SCRAPER_URL}
